import { StyleSheet } from 'react-native';
import { fonts } from '@/components/CoreUI';
import type { Colors } from '@/lib/theme';

export const makeStyles = (c: Colors) => StyleSheet.create({
  container: { flex: 1, backgroundColor: c.canvas, overflow: 'hidden' },
  introTop: { paddingHorizontal: 18 },
  brandBand: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  brandDot: { width: 13, height: 13, borderRadius: 6.5, backgroundColor: c.merah },
  brandText: { fontFamily: fonts.display, fontSize: 20, color: c.ink, letterSpacing: -0.2 },
  chainBadge: { borderWidth: 1, borderColor: c.hairlineStrong, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 99 },
  chainText: { color: c.ink, fontSize: 10, letterSpacing: 1.8 },
  skipText: { fontFamily: fonts.sansSemi, color: c.body, fontSize: 13 },
  sliderShell: { flex: 1, minHeight: 0 },
  slide: { flex: 1, paddingHorizontal: 18, minHeight: 0 },
  visualWrap: { marginTop: 40, alignItems: 'center' },
  visualTokens: { flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center' },
  visualIconBox: {
    width: 84,
    height: 84,
    borderRadius: 22,
    backgroundColor: c.merahSoft,
    borderWidth: 1,
    borderColor: c.merah,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroSection: { marginTop: 40 },
  heroEyebrow: { marginBottom: 16 },
  heroTitle: {
    fontFamily: fonts.display,
    fontSize: 44,
    lineHeight: 45,
    letterSpacing: -1.32,
    color: c.ink,
  },
  heroTitleItalic: { fontFamily: fonts.displayItalic, color: c.merah },
  heroDesc: {
    marginTop: 20,
    fontFamily: fonts.sans,
    fontSize: 15,
    lineHeight: 23,
    color: c.body,
    maxWidth: 330,
  },
  introDock: {
    paddingHorizontal: 18,
    paddingTop: 10,
    backgroundColor: c.canvas,
  },
  dots: { flexDirection: 'row', gap: 7, justifyContent: 'center', marginBottom: 16 },
  dot: { width: 7, height: 7, borderRadius: 99, backgroundColor: c.hairlineStrong },
  dotActive: { width: 22, backgroundColor: c.merah },
  connectButton: {
    minHeight: 56,
    borderRadius: 14,
    backgroundColor: c.accent,
    borderWidth: 1,
    borderColor: c.accent,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    paddingHorizontal: 16,
  },
  inkButton: { backgroundColor: '#16110e', borderColor: '#16110e' },
  connectButtonText: { color: '#fff', fontFamily: fonts.sansSemi, fontSize: 16 },
  ghostButton: { minHeight: 42, alignItems: 'center', justifyContent: 'center', marginTop: 6 },
  ghostButtonText: { fontFamily: fonts.sansSemi, color: c.body, fontSize: 14 },
  liveBadge: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, marginTop: 13 },
  liveDot: { width: 7, height: 7, borderRadius: 3.5, backgroundColor: c.merah },
  liveText: { fontFamily: fonts.sans, color: c.body, fontSize: 12 },
  connectHomeCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  pulseMark: { width: 120, height: 120, alignItems: 'center', justifyContent: 'center', marginBottom: 8 },
  pulseRing: {
    position: 'absolute',
    width: 78,
    height: 78,
    borderRadius: 99,
    borderWidth: 1.5,
    borderColor: c.merah,
    opacity: 0.28,
  },
  pulseRingTwo: {
    position: 'absolute',
    width: 102,
    height: 102,
    borderRadius: 99,
    borderWidth: 1.2,
    borderColor: c.merah,
    opacity: 0.14,
  },
  pulseCore: {
    width: 76,
    height: 76,
    borderRadius: 99,
    backgroundColor: c.merah,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 8,
    borderColor: c.merahSoft,
  },
  pulseCoreText: { fontFamily: fonts.displayMed, fontSize: 34, lineHeight: 38, color: '#fff' },
  welcomeTitle: {
    marginTop: 12,
    fontFamily: fonts.display,
    fontSize: 38,
    lineHeight: 40,
    color: c.ink,
    letterSpacing: -0.76,
    textAlign: 'center',
  },
  welcomeDesc: {
    marginTop: 14,
    fontFamily: fonts.sans,
    fontSize: 14.5,
    lineHeight: 22,
    color: c.body,
    textAlign: 'center',
    maxWidth: 300,
  },
  pulseChips: { flexDirection: 'row', gap: 8, marginTop: 26, flexWrap: 'wrap', justifyContent: 'center' },
  pulseChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingVertical: 7,
    paddingHorizontal: 11,
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.hairline,
    borderRadius: 99,
  },
  pulseChipTicker: { fontFamily: fonts.mono, fontSize: 12, color: c.ink, fontWeight: '600' },
  pulseChipChange: { fontFamily: fonts.mono, fontSize: 11.5, fontWeight: '600' },
  lastWalletRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginBottom: 12 },
  lastWalletIcon: { width: 18, height: 18, borderRadius: 5, alignItems: 'center', justifyContent: 'center' },
  lastWalletGlyph: { fontFamily: fonts.displayMed, fontSize: 10, color: '#fff' },
  lastWalletText: { fontFamily: fonts.sans, color: c.body, fontSize: 12.5 },
  lastWalletName: { fontFamily: fonts.sansSemi, color: c.ink },
  introLink: { alignItems: 'center', marginTop: 6 },
  introLinkText: { fontFamily: fonts.sans, color: c.body, fontSize: 12.5 },
  introLinkAccent: { fontFamily: fonts.sansSemi, color: c.merah },
  modalRoot: { flex: 1, justifyContent: 'flex-end' },
  modalBackdrop: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, backgroundColor: 'rgba(8,6,5,.46)' },
  modalSheet: {
    maxHeight: '88%',
    backgroundColor: c.surface,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    borderTopWidth: 1,
    borderTopColor: c.hairline,
  },
  modalHandleWrap: { alignItems: 'center', paddingTop: 10, paddingBottom: 12 },
  sheetHandle: { backgroundColor: c.hairlineStrong, width: 40, height: 4.5, borderRadius: 3 },
  sheetContent: { paddingHorizontal: 20 },
  sheetTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingBottom: 16 },
  sheetTitle: { fontFamily: fonts.display, fontSize: 21, color: c.ink, letterSpacing: -0.42 },
  sheetClose: {
    width: 32,
    height: 32,
    backgroundColor: c.surface2,
    borderWidth: 1,
    borderColor: c.hairline,
    borderRadius: 99,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetDesc: { marginVertical: 2, marginBottom: 14, color: c.body, fontSize: 13.5, lineHeight: 20, fontFamily: fonts.sans },
  walletList: { gap: 10 },
  walletItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 13,
    paddingHorizontal: 14,
    backgroundColor: c.surface2,
    borderWidth: 1,
    borderColor: c.hairline,
    borderRadius: 18,
  },
  walletIconBox: { width: 38, height: 38, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  walletIconText: { fontFamily: fonts.displayMed, fontSize: 18, color: '#fff' },
  walletFlex: { flex: 1 },
  walletName: { fontFamily: fonts.sansSemi, fontSize: 15, color: c.ink },
  walletStatus: { fontFamily: fonts.sans, fontSize: 12, color: c.body },
  demoNotice: {
    marginTop: 16,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: c.merahSoft,
    borderRadius: 16,
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
  },
  demoNoticeIcon: { marginTop: 1 },
  demoNoticeText: { flex: 1, fontFamily: fonts.sans, fontSize: 12, lineHeight: 18, color: c.inkSoft },
});
