import { StyleSheet } from 'react-native';
import { fonts } from '@/components/CoreUI';
import type { Colors } from '@/lib/theme';

export const makeStyles = (c: Colors) => StyleSheet.create({
  container: { flex: 1, backgroundColor: c.canvas },
  topContent: { flex: 1, paddingHorizontal: 18, justifyContent: 'space-between' },
  brandBand: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  brandDot: { width: 13, height: 13, borderRadius: 6.5, backgroundColor: c.merah },
  brandText: { fontFamily: fonts.display, fontSize: 20, color: c.ink, letterSpacing: -0.2 },
  chainBadge: { marginLeft: 'auto', borderWidth: 1, borderColor: c.hairlineStrong, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 99 },
  chainText: { color: c.ink, fontSize: 10, letterSpacing: 1.8 },
  heroSection: { marginTop: 64, flex: 1 },
  heroEyebrow: { marginBottom: 18 },
  heroTitle: { fontFamily: fonts.display, fontSize: 46, lineHeight: 46, letterSpacing: -1.38, color: c.ink },
  heroTitleItalic: { fontFamily: fonts.displayItalic, color: c.merah },
  heroDesc: { marginTop: 22, fontFamily: fonts.sans, fontSize: 15, lineHeight: 23, color: c.body, maxWidth: 320 },
  statStrip: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: c.hairline, marginBottom: 4 },
  statItem: { flex: 1, paddingVertical: 16 },
  statItemBorder: { borderLeftWidth: 1, borderLeftColor: c.hairline, paddingLeft: 16 },
  statValue: { fontFamily: fonts.display, fontSize: 26, color: c.ink },
  statKey: { marginTop: 4 },
  ctaDock: { paddingHorizontal: 18, paddingTop: 16, borderTopWidth: 1, borderTopColor: c.hairline, backgroundColor: c.surface },
  connectButton: {
    height: 56,
    borderRadius: 14,
    backgroundColor: c.accent,
    borderWidth: 1,
    borderColor: c.accent,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
  },
  connectButtonText: { color: '#fff', fontFamily: fonts.sansSemi, fontSize: 15 },
  liveBadge: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, marginTop: 12 },
  liveDot: { width: 7, height: 7, borderRadius: 3.5, backgroundColor: c.merah },
  liveText: { fontFamily: fonts.sans, color: c.body, fontSize: 12 },
  modalRoot: { flex: 1, justifyContent: 'flex-end' },
  modalBackdrop: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, backgroundColor: 'rgba(8,6,5,.46)' },
  modalSheet: { maxHeight: '88%', backgroundColor: c.surface, borderTopLeftRadius: 26, borderTopRightRadius: 26, borderTopWidth: 1, borderTopColor: c.hairline },
  modalHandleWrap: { alignItems: 'center', paddingTop: 10, paddingBottom: 12 },
  sheetHandle: { backgroundColor: c.hairlineStrong, width: 40, height: 4.5 },
  sheetContent: { paddingHorizontal: 20 },
  sheetTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingBottom: 16 },
  sheetTitle: { fontFamily: fonts.display, fontSize: 21, color: c.ink, letterSpacing: -0.42 },
  sheetClose: { width: 32, height: 32, backgroundColor: c.surface2, borderWidth: 1, borderColor: c.hairline, borderRadius: 99, alignItems: 'center', justifyContent: 'center' },
  sheetDesc: { marginVertical: 2, marginBottom: 14, color: c.body, fontSize: 13.5, lineHeight: 20, fontFamily: fonts.sans },
  walletList: { gap: 10 },
  walletItem: {
    flexDirection: 'row', alignItems: 'center', gap: 14, paddingVertical: 13, paddingHorizontal: 14,
    backgroundColor: c.surface2, borderWidth: 1, borderColor: c.hairline,
    borderRadius: 18,
  },
  walletIconBox: { width: 38, height: 38, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  walletIconText: { fontFamily: fonts.displayMed, fontSize: 18, color: '#fff' },
  walletFlex: { flex: 1 },
  walletName: { fontFamily: fonts.sansSemi, fontSize: 15, color: c.ink },
  walletStatus: { fontFamily: fonts.sans, fontSize: 12, color: c.body },
  demoNotice: { marginTop: 16, paddingVertical: 12, paddingHorizontal: 14, backgroundColor: c.merahSoft, borderRadius: 16, flexDirection: 'row', gap: 10, alignItems: 'flex-start' },
  demoNoticeIcon: { marginTop: 1 },
  demoNoticeText: { flex: 1, fontFamily: fonts.sans, fontSize: 12, lineHeight: 18, color: c.inkSoft },
});
