import { StyleSheet } from 'react-native';
import { fonts } from '@/components/CoreUI';
import type { Colors } from '@/lib/theme';

export const makeStyles = (c: Colors) => StyleSheet.create({
  container: { flex: 1, backgroundColor: c.canvas },
  pad: { paddingHorizontal: 18 },
  heroRow: { flexDirection: 'row', marginTop: 8, gap: 14 },
  heroAmount: { fontFamily: fonts.display, color: c.ink, fontSize: 44, lineHeight: 48, letterSpacing: -0.88 },
  heroChange: { fontFamily: fonts.sansSemi, fontSize: 13.5 },
  heroRange: { fontFamily: fonts.sans, color: c.body, fontSize: 13.5 },
  chartBox: { paddingHorizontal: 6, paddingTop: 8 },
  segmentedBox: { paddingHorizontal: 18, paddingVertical: 8 },
  statsRow: { flexDirection: 'row', paddingHorizontal: 18, paddingTop: 8, gap: 10 },
  statCard: { flex: 1 },
  statTitle: { marginBottom: 8 },
  statValue: { fontSize: 20, fontWeight: '700' },
  statSub: { fontFamily: fonts.sansSemi, fontSize: 12.5 },
  stableText: { fontFamily: fonts.sans, color: c.body, fontSize: 12.5 },
  allocBox: { paddingHorizontal: 18, paddingTop: 12 },
  allocRow: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  donutCenter: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, alignItems: 'center', justifyContent: 'center' },
  donutCount: { fontFamily: fonts.display, color: c.ink, fontSize: 16, letterSpacing: -0.32 },
  donutLabel: { fontSize: 8 },
  legendCol: { flex: 1, gap: 7 },
  legendRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  legendDot: { width: 9, height: 9, borderRadius: 2 },
  legendToken: { fontFamily: fonts.sansSemi, color: c.ink, fontSize: 12.5 },
  legendPct: { marginLeft: 'auto', color: c.body, fontSize: 12 },
  posTitle: { paddingHorizontal: 18, paddingTop: 16, paddingBottom: 4 },
  posList: { marginHorizontal: 18, marginBottom: 16, backgroundColor: c.surface, borderWidth: 1, borderColor: c.hairline, borderRadius: 20, overflow: 'hidden' },
  posItem: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, gap: 12 },
  posFlex: { flex: 1 },
  posTicker: { fontFamily: fonts.sansSemi, color: c.ink, fontSize: 14.5 },
  posSub: { color: c.body, fontSize: 12 },
  posRight: { alignItems: 'flex-end' },
  posValue: { fontSize: 14, fontWeight: '700' },
  posPnl: { fontSize: 11.5, fontWeight: '700' },
});
