import { StyleSheet } from 'react-native';
import { fonts } from '@/components/CoreUI';
import type { Colors } from '@/lib/theme';

export const makeStyles = (c: Colors) => StyleSheet.create({
  container: { flex: 1, backgroundColor: c.canvas },
  settingsButton: { width: 38, height: 38, backgroundColor: c.surface, borderWidth: 1, borderColor: c.hairline, borderRadius: 99, alignItems: 'center', justifyContent: 'center' },
  scrollContainer: { flex: 1, paddingHorizontal: 18 },
  scrollContent: { paddingTop: 6 },
  swapStack: { position: 'relative', gap: 8 },
  swapCard: { overflow: 'visible' },
  unifiedSwapBox: {
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.hairline,
    borderRadius: 20,
    position: 'relative',
  },
  payField: { padding: 16, paddingBottom: 14 },
  receiveField: { padding: 16, paddingTop: 14 },
  divider: { height: 1, backgroundColor: c.hairline, marginHorizontal: 16 },
  fieldHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  balanceText: { fontFamily: fonts.sans, color: c.body, fontSize: 11.5 },
  insufficientBalanceText: { fontFamily: fonts.sans, color: c.merah, fontSize: 11.5 },
  fieldInputContainer: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  amountInput: {
    flex: 1,
    fontFamily: fonts.mono,
    color: c.ink,
    fontSize: 32,
    fontWeight: '700',
    padding: 0,
  },
  amountText: {
    flex: 1,
    fontFamily: fonts.mono,
    color: c.ink,
    fontSize: 32,
    fontWeight: '700',
  },
  amountTextEmpty: {
    flex: 1,
    fontFamily: fonts.mono,
    color: c.hairlineStrong,
    fontSize: 32,
    fontWeight: '700',
  },
  tokenButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.surface2,
    borderWidth: 1,
    borderColor: c.hairline,
    borderRadius: 99,
    gap: 8,
    paddingVertical: 7,
    paddingLeft: 8,
    paddingRight: 11,
  },
  tokenButtonText: { fontFamily: fonts.sansSemi, color: c.ink, fontSize: 15 },
  fieldFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10 },
  usdValueText: { fontFamily: fonts.mono, color: c.body, fontSize: 12.5 },
  percentageButtonsContainer: { flexDirection: 'row', gap: 6 },
  percentageButton: {
    borderWidth: 1,
    borderColor: c.hairline,
    backgroundColor: c.surface2,
    borderRadius: 99,
    paddingVertical: 4,
    paddingHorizontal: 9,
  },
  percentageButtonText: {
    fontFamily: fonts.sansSemi,
    color: c.body,
    fontSize: 11,
  },
  flipButtonContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -20 }, { translateY: -20 }],
    zIndex: 10,
  },
  flipButton: {
    width: 40,
    height: 40,
    borderRadius: 99,
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.hairlineStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailsContainer: { marginTop: 14, paddingHorizontal: 4, gap: 9 },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  detailLabel: { fontFamily: fonts.sans, color: c.body, fontSize: 12.5 },
  detailValue: { fontFamily: fonts.mono, color: c.ink, fontSize: 12.5, fontWeight: '600' },
  detailValueSans: { fontFamily: fonts.sans, color: c.ink, fontSize: 12.5, fontWeight: '600' },
  slippageContainer: { flexDirection: 'row', gap: 5 },
  slippageButton: {
    borderWidth: 1,
    borderRadius: 99,
    paddingVertical: 3,
    paddingHorizontal: 9,
  },
  slippageButtonText: {
    fontFamily: fonts.sansSemi,
    fontSize: 11,
  },
  bottomBar: {
    backgroundColor: c.surface,
    borderTopWidth: 1,
    borderTopColor: c.hairline,
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 12,
  },
  reviewTokensContainer: { flexDirection: 'row', alignItems: 'center', paddingVertical: 16, gap: 12 },
  reviewTokenBox: { flex: 1, alignItems: 'center' },
  reviewTokenAmount: { fontFamily: fonts.mono, fontSize: 17, fontWeight: '700', marginTop: 8, color: c.ink },
  reviewTokenTicker: { fontFamily: fonts.sans, color: c.body, fontSize: 12 },
  reviewDetailsCard: { backgroundColor: c.surface2, paddingHorizontal: 14, paddingVertical: 4, borderRadius: 16, borderWidth: 1, borderColor: c.hairline },
  reviewDetailRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 11 },
  reviewDetailRowBorder: { borderBottomWidth: 1, borderBottomColor: c.hairline },
  reviewDetailLabel: { fontFamily: fonts.sans, color: c.body, fontSize: 13 },
  reviewDetailValue: { fontFamily: fonts.mono, color: c.ink, fontSize: 13, fontWeight: '600' },
  confirmButtonContainer: { marginTop: 16 },
  successContainer: { alignItems: 'center', paddingVertical: 10 },
  successIconBox: { width: 66, height: 66, backgroundColor: c.positive, borderRadius: 33, alignItems: 'center', justifyContent: 'center', marginTop: 6 },
  successTitle: { fontFamily: fonts.display, color: c.ink, fontSize: 24, marginTop: 16 },
  successSubtitle: { fontFamily: fonts.sans, color: c.body, fontSize: 13.5, marginTop: 6 },
  successHighlight: { color: c.ink, fontWeight: 'bold' },
  successMeta: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 12 },
  successMetaText: { fontFamily: fonts.sans, color: c.body, fontSize: 12 },
  successDoneContainer: { alignSelf: 'stretch', marginTop: 20 },
  tokenSelectRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, paddingHorizontal: 4, gap: 12 },
  tokenSelectInfo: { flex: 1 },
  tokenSelectTicker: { fontFamily: fonts.sansSemi, color: c.ink, fontSize: 14.5 },
  tokenSelectName: { fontFamily: fonts.sans, color: c.body, fontSize: 12 },
  tokenSelectBalance: { fontFamily: fonts.mono, fontSize: 12.5 },
  modalRoot: { flex: 1, justifyContent: 'flex-end' },
  modalBackdrop: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, backgroundColor: 'rgba(8,6,5,.46)' },
  modalSheet: { maxHeight: '86%', backgroundColor: c.surface, borderTopLeftRadius: 26, borderTopRightRadius: 26, borderTopWidth: 1, borderTopColor: c.hairline },
  modalHandleWrap: { alignItems: 'center', paddingTop: 10, paddingBottom: 10 },
  modalHandle: { width: 40, height: 4.5, borderRadius: 3, backgroundColor: c.hairlineStrong },
  modalTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingBottom: 6 },
  modalTitle: { fontFamily: fonts.display, fontSize: 21, color: c.ink, letterSpacing: -0.42 },
  modalClose: { width: 32, height: 32, backgroundColor: c.surface2, borderWidth: 1, borderColor: c.hairline, borderRadius: 99, alignItems: 'center', justifyContent: 'center' },
  tokenSearchBox: {
    marginHorizontal: 20,
    marginTop: 8,
    marginBottom: 10,
    height: 40,
    borderRadius: 99,
    borderWidth: 1,
    borderColor: c.hairline,
    backgroundColor: c.surface2,
    paddingHorizontal: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  tokenSearchInput: { flex: 1, padding: 0, fontFamily: fonts.sans, color: c.ink, fontSize: 13 },
  emptySearchText: { fontFamily: fonts.sans, color: c.body, fontSize: 13, textAlign: 'center', paddingVertical: 18 },
  modalContent: { paddingHorizontal: 20, paddingBottom: 24 },
  settingsContent: { paddingHorizontal: 20, paddingBottom: 24 },
  settingsRow: { minHeight: 62, borderRadius: 16, backgroundColor: c.surface2, borderWidth: 1, borderColor: c.hairline, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  settingsTitle: { fontFamily: fonts.sansSemi, color: c.ink, fontSize: 15 },
  settingsSubtitle: { fontFamily: fonts.sans, color: c.body, fontSize: 12, marginTop: 2 },
  switchTrack: { width: 46, height: 28, borderRadius: 99, backgroundColor: c.hairlineStrong, padding: 3, justifyContent: 'center' },
  switchTrackOn: { backgroundColor: c.merah },
  switchThumb: { width: 22, height: 22, borderRadius: 99, backgroundColor: c.surface },
  switchThumbOn: { alignSelf: 'flex-end' },
  sheetEyebrow: { marginTop: 14, marginBottom: 4 },
  sheetEyebrowFirst: { marginTop: 4, marginBottom: 4 },
});
